# Generated by Django 3.2.4 on 2021-07-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Catégorie')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='mot')),
            ],
        ),
        migrations.CreateModel(
            name='TypeJuridiction',
            fields=[
                ('cle', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Abbréviation')),
                ('nom', models.CharField(max_length=40, verbose_name='Type')),
                ('niveau', models.IntegerField(help_text='Niveau de hiérarchie (1=première instance, 2 ensuite, etc...)', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Type de Juridiction',
                'verbose_name_plural': 'Types de Juridiction',
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.categorie')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representant_of', to='search.mot')),
            ],
            options={
                'verbose_name': 'Mot-clé',
                'verbose_name_plural': 'Mots-clés',
                'ordering': ['representant'],
            },
        ),
        migrations.AddField(
            model_name='mot',
            name='motcle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='search.motcle'),
        ),
        migrations.CreateModel(
            name='Juridiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=70, null=True)),
                ('ville', models.CharField(blank=True, max_length=40, null=True)),
                ('rattachement', models.ForeignKey(blank=True, help_text="Cour d'Appel de rattachement dans le cas d'un Conseil des Prud'Hommes", limit_choices_to={'type_juridiction': 'CA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.juridiction', verbose_name='Cour de rattachement')),
                ('type_juridiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.typejuridiction')),
            ],
            options={
                'ordering': ['type_juridiction', 'ville'],
            },
        ),
        migrations.CreateModel(
            name='Jugement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='jugements', verbose_name='Fichier')),
                ('lisible', models.BooleanField(help_text="Vrai si le fichier est lisible par l'ordinateur.", verbose_name='Lisible')),
                ('decision', models.CharField(blank=True, choices=[('F', 'Favorable'), ('D', 'Défavorable'), ('M', 'Mixte')], help_text='Décision de justice', max_length=1, null=True, verbose_name='Décision')),
                ('date_jugement', models.DateField(blank=True, help_text='Date du jugement', null=True, verbose_name='Date du jugement')),
                ('gain', models.FloatField(blank=True, help_text='Somme gagnée lors du procès (négative si perdu)', null=True, verbose_name='Somme gagnée')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import du jugement")),
                ('agent_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.agent', verbose_name="Agent l'ayant importé")),
                ('juridiction', models.ForeignKey(blank=True, help_text='Cour ou Conseil du jugement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.typejuridiction', verbose_name='Juridiction')),
                ('mots_cle', models.ManyToManyField(blank=True, help_text='Mots-clé présents dans le Jugement', to='search.MotCle', verbose_name='Mot-Clé')),
            ],
            options={
                'verbose_name': 'Décision de justice',
                'verbose_name_plural': 'Décisions de justice',
                'ordering': ['-date_jugement'],
            },
        ),
    ]
