# Generated by Django 3.2.4 on 2021-07-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugement',
            name='lisible',
            field=models.BooleanField(help_text="Vrai si le fichier est lisible par l'ordinateur.", null=True, verbose_name='Lisible'),
        ),
    ]
