# Generated by Django 3.2.4 on 2021-07-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_jugement_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugement',
            name='nom',
            field=models.CharField(default='Nom', help_text='Nom du fichier', max_length=200, verbose_name='Nom du fichier'),
            preserve_default=False,
        ),
    ]
