# Generated by Django 3.2.4 on 2021-07-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_jugement_lisible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridiction',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
