# Generated by Django 3.2.4 on 2021-07-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210705_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugement',
            name='nom',
        ),
    ]
