# Generated by Django 3.2.4 on 2021-07-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_juridiction_type_juridiction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugement',
            name='juridiction',
            field=models.ForeignKey(blank=True, help_text='Cour ou Conseil du jugement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.juridiction', verbose_name='Juridiction'),
        ),
    ]
