# Generated by Django 3.2.4 on 2021-07-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_alter_jugement_juridiction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugement',
            name='mots_cle',
        ),
        migrations.AddField(
            model_name='jugement',
            name='mots_cles',
            field=models.ManyToManyField(blank=True, help_text='Mots-clés présents dans le Jugement', to='search.MotCle', verbose_name='Mot-Clé'),
        ),
    ]
