# Generated by Django 3.2.4 on 2021-07-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20210716_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typejuridiction',
            name='cle',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Abbréviation'),
        ),
    ]
