# Generated by Django 3.2.4 on 2021-07-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_alter_typejuridiction_cle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugement',
            name='mots_cles',
            field=models.ManyToManyField(blank=True, help_text='Mots-clés présents dans le Jugement', to='search.MotCle', verbose_name='Mots-Clés'),
        ),
    ]
