# Generated by Django 3.2.4 on 2021-07-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_alter_typejuridiction_cle'),
    ]

    operations = [
        migrations.AddField(
            model_name='typejuridiction',
            name='regex',
            field=models.CharField(default='', max_length=50, verbose_name='Expression régulière'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugement',
            name='mots_cles',
            field=models.ManyToManyField(blank=True, help_text='Mots-clés présents dans le Jugement', to='search.MotCle', verbose_name='Mots-Clés'),
        ),
        migrations.AlterField(
            model_name='typejuridiction',
            name='cle',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Abbréviation'),
        ),
    ]
