# Generated by Django 3.2.4 on 2021-07-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20210721_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugement',
            name='date_jugement',
            field=models.DateField(blank=True, null=True, verbose_name='Date du jugement'),
        ),
        migrations.AlterField(
            model_name='jugement',
            name='decision',
            field=models.CharField(blank=True, choices=[('F', 'Favorable'), ('D', 'Défavorable'), ('M', 'Mixte')], max_length=1, null=True, verbose_name='Décision'),
        ),
        migrations.AlterField(
            model_name='jugement',
            name='juridiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.juridiction', verbose_name='Juridiction'),
        ),
        migrations.AlterField(
            model_name='jugement',
            name='lisible',
            field=models.BooleanField(default=False, verbose_name='Lisible'),
        ),
    ]
