# Generated by Django 3.2.4 on 2021-07-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_alter_jugement_mots_cles'),
        ('search', '0011_auto_20210721_0935'),
    ]

    operations = [
    ]
