# Generated by Django 3.2.4 on 2021-07-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20210722_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugement',
            name='lisible',
            field=models.BooleanField(null=True, verbose_name='Lisible'),
        ),
    ]
