# Generated by Django 3.2.4 on 2021-07-08 12:36

from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('search', '0002_alter_jugement_lisible'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JugementTemp_Mots_Cle',
            fields=[
                ('mots_cle', models.ForeignKey(blank=True, help_text='Mots-clé présents dans le Jugement', on_delete=django.db.models.deletion.CASCADE, to='search.MotCle', verbose_name='Mot-Clé')),
            ],
        ),
    ]