# Generated by Django 3.2.4 on 2021-07-12 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0003_alter_juridiction_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='JugementTemp',
            fields=[
                ('jugement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.jugement')),
                ('doublon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doublons', to='search.jugement')),
            ],
            options={
                'verbose_name': 'Décision non validée',
                'verbose_name_plural': 'Décisions non validées',
                'ordering': ['-date_import'],
            },
            bases=('search.jugement',),
        ),
    ]
