# Generated by Django 3.2.4 on 2021-07-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_jugement_lisible'),
        ('add_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugementtemp',
            name='doublon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.jugement'),
        ),
    ]
