# Generated by Django 3.2.4 on 2021-07-13 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0003_alter_juridiction_nom'),
        ('account', '0001_initial'),
        ('add_file', '0002_delete_jugementtemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='JugementTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lisible', models.BooleanField(help_text="Vrai si le fichier est lisible par l'ordinateur.", null=True, verbose_name='Lisible')),
                ('decision', models.CharField(blank=True, choices=[('F', 'Favorable'), ('D', 'Défavorable'), ('M', 'Mixte')], help_text='Décision de justice', max_length=1, null=True, verbose_name='Décision')),
                ('date_jugement', models.DateField(blank=True, help_text='Date du jugement', null=True, verbose_name='Date du jugement')),
                ('gain', models.FloatField(blank=True, help_text='Somme gagnée lors du procès (négative si perdu)', null=True, verbose_name='Somme gagnée')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import du jugement")),
                ('file', models.FileField(upload_to='jugements/temp', verbose_name='Fichier')),
                ('agent_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.agent', verbose_name="Agent l'ayant importé")),
                ('doublon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.jugement')),
                ('juridiction', models.ForeignKey(blank=True, help_text='Cour ou Conseil du jugement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.typejuridiction', verbose_name='Juridiction')),
                ('mots_cle', models.ManyToManyField(blank=True, help_text='Mots-clé présents dans le Jugement', to='search.MotCle', verbose_name='Mot-Clé')),
            ],
            options={
                'verbose_name': 'Décision non validée',
                'verbose_name_plural': 'Décisions non validées',
                'ordering': ['-date_import'],
            },
        ),
    ]
