# Generated by Django 3.2.4 on 2021-07-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_file', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jugementtemp_mots_cle',
        ),
    ]
