# Generated by Django 3.2.4 on 2021-07-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_file', '0004_jugementtemp_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugementtemp',
            name='lisible',
        ),
        migrations.AddField(
            model_name='jugementtemp',
            name='quality',
            field=models.FloatField(help_text='Indice de qualité du PDF analysé', null=True, verbose_name='Qualité'),
        ),
    ]
