# Generated by Django 3.2.4 on 2021-07-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_file', '0005_auto_20210713_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugementtemp',
            name='lisible',
            field=models.BooleanField(help_text="Vrai si le fichier est lisible par l'ordinateur.", null=True, verbose_name='Lisible'),
        ),
    ]
