# Generated by Django 3.2.4 on 2021-07-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20210721_0935'),
        ('add_file', '0006_auto_20210716_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugementtemp',
            name='mots_cles',
            field=models.ManyToManyField(blank=True, help_text='Mots-clés présents dans le Jugement', to='search.MotCle', verbose_name='Mots-Clés'),
        ),
    ]
