# Generated by Django 3.2.4 on 2021-07-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_profil_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
        migrations.AlterField(
            model_name='agent',
            name='responsable',
            field=models.BooleanField(default=False, help_text='Vrai si le responsable est actuellement en charge.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='telephone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Téléphone'),
        ),
    ]
